package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/caasmo/restinpieces-backup-client/ssh"
	ripbackup "github.com/caasmo/restinpieces/backup"
	"github.com/gokrazy/rsync/rsyncclient"
	"zombiezen.com/go/sqlite"
)

func main() {
	useLocal := flag.Bool("l", false, "run rsync on the same machine instead of over SSH")
	flag.BoolVar(useLocal, "local", false, "run rsync on the same machine instead of over SSH")
	flag.Parse()

	if err := run(*useLocal); err != nil {
		slog.Error("Backup failed", "error", err)
		os.Exit(1)
	}
}

// run reads configuration, creates the rsync client and its server
// arguments, dispatches to the SSH or local connection path, logs the
// transfer statistics, and runs the post-transfer verification.
func run(useLocal bool) error {
	sourceDir := os.Getenv("RIP_BCK_SOURCE_DIR")
	destDir := os.Getenv("RIP_BCK_DEST_DIR")

	switch {
	case sourceDir == "":
		return fmt.Errorf("RIP_BCK_SOURCE_DIR is required")
	case destDir == "":
		return fmt.Errorf("RIP_BCK_DEST_DIR is required")
	}

	ctx := context.Background()

	err := os.MkdirAll(destDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create destination directory: %w", err)
	}

	slog.Info("Starting rsync backup client")

	// Create the rsync client. We do NOT use WithSender() because we are
	// the receiver (pulling from the server to local disk).
	//
	// rsyncclient writes to a temp file and atomically renames on success.
	// If the transfer or checksum fails, the destination file is never
	// touched.
	rsyncClient, err := rsyncclient.New([]string{"-av"})
	if err != nil {
		return fmt.Errorf("failed to create rsync client: %w", err)
	}

	// ServerCommandOptions returns the arguments to pass to the rsync
	// binary in server mode, generated by gokrazy from the client's own
	// options (e.g. --server --sender -vlogDtpr . /path/to/latest-*.db).
	// path.Join ensures / separators regardless of OS and preserves the
	// glob pattern. ripbackup.LatestGlob ("latest-*.db") is the shared
	// contract from the restinpieces backup package: it selects every
	// latest-<backupID> hard link the server maintains, excluding the
	// transient "<name>.db.tmp" link-atomicity artifact and never
	// matching timestamped snapshots.
	globPath := path.Join(sourceDir, ripbackup.LatestGlob)
	serverArgs := rsyncClient.ServerCommandOptions(globPath)

	// Connection selection: the -l/--local flag runs rsync on the same
	// machine; the default connects over SSH.
	var result *rsyncclient.Result
	if useLocal {
		result, err = backupLocal(ctx, rsyncClient, destDir, globPath, serverArgs)
	} else {
		result, err = backupSSH(ctx, rsyncClient, destDir, globPath, serverArgs)
	}
	if err != nil {
		return err
	}

	slog.Info("rsync transfer completed",
		"bytes_read", result.Stats.Read,
		"bytes_written", result.Stats.Written,
		"total_size", result.Stats.Size,
	)

	err = verifyBackup(destDir)
	if err != nil {
		return fmt.Errorf("backup verification failed: %w", err)
	}

	return nil
}

// backupSSH dials the SSH server, starts the remote rsync binary in
// server mode over a session, and delegates to transfer.
func backupSSH(ctx context.Context, rsyncClient *rsyncclient.Client, destDir, globPath string, serverArgs []string) (result *rsyncclient.Result, err error) {
	cfg, err := ssh.ConfigFromEnv()
	if err != nil {
		return nil, fmt.Errorf("failed to read SSH config: %w", err)
	}

	client, err := ssh.Dial(cfg)
	if err != nil {
		return nil, fmt.Errorf("failed to dial ssh: %w", err)
	}
	defer func() {
		closeErr := client.Close()
		err = errors.Join(err, closeErr)
	}()

	// Args are joined unquoted: session.Start runs the command through
	// the remote login shell, which splits it and expands the source
	// glob (latest-*.db) into the concrete files the sender transfers.
	// On zero matches the shell leaves the literal pattern in place,
	// which the sender then fails on. The source directory must be free
	// of shell metacharacters. backupLocal performs the same expansion
	// in Go, because its exec.Command runs the binary without a shell.
	remoteCmd := fmt.Sprintf("rsync %s", strings.Join(serverArgs, " "))
	session, err := ssh.NewSession(client, remoteCmd)
	if err != nil {
		return nil, err
	}
	defer func() {
		closeErr := session.Close()
		err = errors.Join(err, closeErr)
	}()

	return transfer(ctx, rsyncClient, destDir, globPath, session.Pipe(), session.Wait)
}

// backupLocal starts the local rsync binary in server mode and
// delegates to transfer.
func backupLocal(ctx context.Context, rsyncClient *rsyncclient.Client, destDir, globPath string, serverArgs []string) (result *rsyncclient.Result, err error) {
	// exec.Command runs the rsync binary without a shell, so the source
	// glob in serverArgs would reach the sender literally and fail. The
	// SSH path gets its expansion from the remote login shell
	// (backupSSH); here the same expansion happens in Go. The glob is
	// the trailing serverArgs element: ServerCommandOptions appends the
	// source path last, after the server options and the "." module
	// marker. Zero matches fail before the process is spawned.
	matches, err := filepath.Glob(globPath)
	if err != nil {
		return nil, fmt.Errorf("failed to glob source directory: %w", err)
	}
	if len(matches) == 0 {
		return nil, fmt.Errorf("no backup files received: server glob matched nothing: %s", globPath)
	}

	serverArgs = append(serverArgs[:len(serverArgs)-1], matches...)

	cmd := exec.CommandContext(ctx, "rsync", serverArgs...)
	cmd.Stderr = os.Stderr

	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("failed to get stdin pipe: %w", err)
	}

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, errors.Join(fmt.Errorf("failed to get stdout pipe: %w", err), stdin.Close())
	}

	err = cmd.Start()
	if err != nil {
		// os/exec already closed the parent-side pipes on failure
		// (Cmd.Start closes parentIOPipes when the process did not start).
		return nil, fmt.Errorf("failed to start local rsync: %w", err)
	}

	rw := &struct {
		io.Reader
		io.Writer
	}{Reader: stdout, Writer: stdin}

	// wait closes stdin to signal the local rsync process that the
	// transfer is done, then blocks until the process exits.
	wait := func() error {
		var errs []error
		closeErr := stdin.Close()
		errs = append(errs, closeErr)
		waitErr := cmd.Wait()
		errs = append(errs, waitErr)
		cmd = nil
		return errors.Join(errs...)
	}

	// Kill the local rsync process if the transfer failed before wait
	// could reap it. The protocol failed, so stdin EOF cannot be relied
	// on for graceful termination — SIGKILL is the deterministic teardown.
	defer func() {
		if cmd != nil {
			killErr := cmd.Process.Kill()
			reapErr := cmd.Wait() // reap the killed process, prevent zombie
			err = errors.Join(err, killErr, reapErr)
			cmd = nil
		}
	}()

	return transfer(ctx, rsyncClient, destDir, globPath, rw, wait)
}

// transfer runs the rsync protocol over rw and waits for the server
// process to exit, returning the transfer statistics.
func transfer(ctx context.Context, rsyncClient *rsyncclient.Client, destDir, globPath string, rw io.ReadWriter, wait func() error) (*rsyncclient.Result, error) {
	// Pass the destination DIRECTORY: the receiver treats it as a
	// directory (verified in clientmaincmd.go: os.MkdirAll + os.OpenRoot)
	// and writes each file into it under its source name.
	result, err := rsyncClient.Run(ctx, rw, []string{destDir})
	if err != nil {
		return nil, fmt.Errorf("rsync transfer failed: %w", err)
	}

	// Zero-match glob is a failure, not a success: the sender must
	// transfer at least one file. Both paths detect the empty file list
	// before this check — the local path in backupLocal (Go glob before
	// spawning), the SSH path in the sender, which fails on the literal
	// pattern the shell leaves in place — so this size check is the
	// final guard. The sender's final stats report the total size of
	// files (the sum of the file-list lengths), which is zero iff the
	// file list was empty, even when stale files from a database
	// removed from the server's config linger in the destination
	// directory and would make the local glob match. Stats is always
	// non-nil after a successful Run (verified in source v0.3.4: Run
	// wraps the stats from maincmd.ClientRun into &Result{Stats}).
	if result == nil || result.Stats == nil || result.Stats.Size == 0 {
		return nil, fmt.Errorf("no backup files received: server glob matched nothing: %s", globPath)
	}

	// Wait closes stdin and blocks until the server process exits. A
	// nonzero exit after a successful protocol run is a server-side
	// failure (e.g. the sender could not read a matched file), so the
	// run fails instead of silently accepting the transfer.
	waitErr := wait()
	if waitErr != nil {
		return nil, fmt.Errorf("rsync server process exited with error: %w", waitErr)
	}

	return result, nil
}

// verifyBackup sanity-checks the received files: at least one latest-*
// file must be present in the destination directory, none may be empty,
// and every file must pass the SQLite integrity check. The zero-match
// failure itself is detected earlier (the Go glob in backupLocal, or
// the SSH sender failing on the literal pattern, with the transfer
// stats size check as final guard); this glob check is the sanity
// check that the files actually landed in the destination directory.
// Verification is deliberately non-cancellable: it is a local read-only
// scan of files already on disk, and process-level interruption
// (SIGINT) applies.
func verifyBackup(destDir string) error {
	localLatestGlob := filepath.Join(destDir, ripbackup.LatestGlob)
	latestFiles, err := filepath.Glob(localLatestGlob)
	if err != nil {
		return fmt.Errorf("failed to glob destination directory: %w", err)
	}
	if len(latestFiles) == 0 {
		return fmt.Errorf("no backup files found in destination directory: %s", localLatestGlob)
	}

	var emptyErrs []error
	for _, localPath := range latestFiles {
		fi, statErr := os.Stat(localPath)
		if statErr != nil {
			return fmt.Errorf("failed to stat local file post rsync: %w", statErr)
		}

		if fi.Size() == 0 {
			removeErr := os.Remove(localPath)
			emptyErr := fmt.Errorf("local backup file is empty post rsync: %s", localPath)
			emptyErrs = append(emptyErrs, errors.Join(emptyErr, removeErr))
			continue
		}

		err = verifySqliteIntegrity(localPath)
		if err != nil {
			return fmt.Errorf("backup verification failed post rsync: %w", err)
		}
		slog.Info("Backup verification successful. Local SQLite database is valid.", "path", localPath)
	}

	if len(emptyErrs) > 0 {
		return errors.Join(emptyErrs...)
	}

	return nil
}

func verifySqliteIntegrity(dbPath string) (err error) {
	// Opening a WAL-mode database read-only initializes the WAL
	// infrastructure and leaves two artifacts next to the database in
	// the destination directory: the -shm wal-index (32768 bytes) and
	// the -wal file. Both are always inert here: the connection is
	// read-only and integrity_check never writes, so the -wal stays at
	// 0 bytes and the wal-index describes an empty WAL. On later runs
	// the same artifact names are reused — the stale index is validated
	// against the empty -wal on open and discarded, and every page is
	// read from the .db file alone, so the verification result is never
	// affected. The artifacts hold no backup data and are ignored by
	// the latest-*.db glob.
	conn, err := sqlite.OpenConn(dbPath, sqlite.OpenReadOnly)
	if err != nil {
		return fmt.Errorf("failed to open database for verification: %w", err)
	}
	defer func() {
		closeErr := conn.Close()
		err = errors.Join(err, closeErr)
	}()

	stmt, err := conn.Prepare("PRAGMA integrity_check;")
	if err != nil {
		return fmt.Errorf("failed to prepare integrity_check statement: %w", err)
	}
	defer func() {
		finalizeErr := stmt.Finalize()
		err = errors.Join(err, finalizeErr)
	}()

	// integrity_check returns a single "ok" row when the database is
	// healthy, or one row per problem otherwise — the first row decides
	// pass/fail, so the result set need not be exhausted.
	row, err := stmt.Step()
	if err != nil {
		return fmt.Errorf("failed to execute integrity_check: %w", err)
	}
	if !row {
		return fmt.Errorf("integrity_check returned no rows")
	}

	result := stmt.ColumnText(0)
	if result != "ok" {
		return fmt.Errorf("integrity_check failed, result was: %s", result)
	}

	return nil
}
