package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path"
	"path/filepath"

	"github.com/caasmo/restinpieces-backup-client/transport"
	"github.com/caasmo/restinpieces-backup-client/transport/local"
	sshtransport "github.com/caasmo/restinpieces-backup-client/transport/ssh"
	ripbackup "github.com/caasmo/restinpieces/backup"
	"github.com/gokrazy/rsync/rsyncclient"
	"zombiezen.com/go/sqlite"
)

func main() {
	useLocal := flag.Bool("l", false, "run rsync on the same machine (local transport) instead of over SSH")
	flag.BoolVar(useLocal, "local", false, "run rsync on the same machine (local transport) instead of over SSH")
	flag.Parse()

	if err := run(*useLocal); err != nil {
		slog.Error("Backup failed", "error", err)
		os.Exit(1)
	}
}

// run reads configuration, constructs the selected transport, and
// delegates to the transport-agnostic backup function.
func run(useLocal bool) error {
	sourceDir := os.Getenv("RIP_BCK_SOURCE_DIR")
	destDir := os.Getenv("RIP_BCK_DEST_DIR")

	switch {
	case sourceDir == "":
		return fmt.Errorf("RIP_BCK_SOURCE_DIR is required")
	case destDir == "":
		return fmt.Errorf("RIP_BCK_DEST_DIR is required")
	}

	ctx := context.Background()

	// Transport selection: the -l/--local flag selects the local
	// transport (rsync on the same machine); the default is the SSH
	// transport.
	var t transport.Transport
	switch {
	case useLocal:
		t = local.New()
	default:
		cfg, err := sshtransport.ConfigFromEnv()
		if err != nil {
			return fmt.Errorf("failed to read SSH config: %w", err)
		}
		t, err = sshtransport.New(cfg)
		if err != nil {
			return fmt.Errorf("failed to connect SSH: %w", err)
		}
	}

	return backup(ctx, t, sourceDir, destDir)
}

// backup is the transport-agnostic core: it creates the rsync client,
// connects via the transport, runs the rsync protocol, waits for the
// server process, and verifies the received databases. One defer t.Close()
// covers every return path.
func backup(ctx context.Context, t transport.Transport, sourceDir, destDir string) (err error) {
	defer func() {
		closeErr := t.Close()
		err = errors.Join(err, closeErr)
	}()

	slog.Info("Starting rsync backup client")

	err = os.MkdirAll(destDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create destination directory: %w", err)
	}

	// Create the rsync client. We do NOT use WithSender() because we are
	// the receiver (pulling from the server to local disk).
	//
	// rsyncclient writes to a temp file and atomically renames on success.
	// If the transfer or checksum fails, the destination file is never
	// touched.
	rsyncClient, err := rsyncclient.New([]string{"-av"})
	if err != nil {
		return fmt.Errorf("failed to create rsync client: %w", err)
	}

	// ServerCommandOptions returns the arguments to pass to the rsync
	// binary in server mode, generated by gokrazy from the client's own
	// options (e.g. --server --sender -vlogDtpr . /path/to/latest-*.db).
	// path.Join ensures / separators regardless of OS and preserves the
	// glob pattern. ripbackup.LatestGlob ("latest-*.db") is the shared
	// contract from the restinpieces backup package: it selects every
	// latest-<backupID> hard link the server maintains, excluding the
	// transient "<name>.db.tmp" link-atomicity artifact and never
	// matching timestamped snapshots.
	globPath := path.Join(sourceDir, ripbackup.LatestGlob)
	serverArgs := rsyncClient.ServerCommandOptions(globPath)

	// Connect starts the rsync server process (remote via SSH, local via
	// exec.Command) and returns the io.ReadWriter the protocol runs over.
	rw, err := t.Connect(ctx, serverArgs)
	if err != nil {
		return fmt.Errorf("failed to connect transport: %w", err)
	}

	// Pass the destination DIRECTORY: the receiver treats it as a
	// directory (verified in clientmaincmd.go: os.MkdirAll + os.OpenRoot)
	// and writes each file into it under its source name.
	result, err := rsyncClient.Run(ctx, rw, []string{destDir})
	if err != nil {
		return fmt.Errorf("rsync transfer failed: %w", err)
	}

	// Zero-match glob is a failure, not a success: when no latest-*.db
	// exists, the shell leaves the literal pattern in place, the sender
	// transfers zero files, and the protocol completes without error.
	// The sender's final stats report the total size of files (the sum
	// of the file-list lengths), which is zero iff the file list was
	// empty — so a zero size means nothing was received, even when
	// stale files from a database removed from the server's config
	// linger in the destination directory and would make the local glob
	// match. Stats is always non-nil after a successful Run (verified
	// in source v0.3.4: Run wraps the stats from maincmd.ClientRun
	// into &Result{Stats}).
	if result == nil || result.Stats == nil || result.Stats.Size == 0 {
		return fmt.Errorf("no backup files received: server glob matched nothing: %s", globPath)
	}

	// Wait closes stdin and blocks until the server process exits. A
	// nonzero exit after a successful protocol run is a server-side
	// failure (e.g. the sender could not read a matched file), so the
	// run fails instead of silently accepting the transfer.
	waitErr := t.Wait()
	if waitErr != nil {
		return fmt.Errorf("rsync server process exited with error: %w", waitErr)
	}

	slog.Info("rsync transfer completed",
		"bytes_read", result.Stats.Read,
		"bytes_written", result.Stats.Written,
		"total_size", result.Stats.Size,
	)

	err = verifyBackup(destDir)
	if err != nil {
		return fmt.Errorf("backup verification failed: %w", err)
	}

	return nil
}

// verifyBackup sanity-checks the received files: at least one latest-*
// file must be present in the destination directory, none may be empty,
// and every file must pass the SQLite integrity check. The zero-match
// failure itself is detected in backup() from the transfer stats (total
// size zero means the sender's file list was empty); this glob check is
// the sanity check that the files actually landed in the destination
// directory. Verification is deliberately non-cancellable: it is a
// local read-only scan of files already on disk, and process-level
// interruption (SIGINT) applies.
func verifyBackup(destDir string) error {
	localLatestGlob := filepath.Join(destDir, ripbackup.LatestGlob)
	latestFiles, err := filepath.Glob(localLatestGlob)
	if err != nil {
		return fmt.Errorf("failed to glob destination directory: %w", err)
	}
	if len(latestFiles) == 0 {
		return fmt.Errorf("no backup files found in destination directory: %s", localLatestGlob)
	}

	var emptyErrs []error
	for _, localPath := range latestFiles {
		fi, statErr := os.Stat(localPath)
		if statErr != nil {
			return fmt.Errorf("failed to stat local file post rsync: %w", statErr)
		}

		if fi.Size() == 0 {
			removeErr := os.Remove(localPath)
			emptyErr := fmt.Errorf("local backup file is empty post rsync: %s", localPath)
			emptyErrs = append(emptyErrs, errors.Join(emptyErr, removeErr))
			continue
		}

		err = verifyIntegrity(localPath)
		if err != nil {
			return fmt.Errorf("backup verification failed post rsync: %w", err)
		}
		slog.Info("Backup verification successful. Local SQLite database is valid.", "path", localPath)
	}

	if len(emptyErrs) > 0 {
		return errors.Join(emptyErrs...)
	}

	return nil
}

func verifyIntegrity(dbPath string) (err error) {
	conn, err := sqlite.OpenConn(dbPath, sqlite.OpenReadOnly)
	if err != nil {
		return fmt.Errorf("failed to open database for verification: %w", err)
	}
	defer func() {
		closeErr := conn.Close()
		err = errors.Join(err, closeErr)
	}()

	stmt, err := conn.Prepare("PRAGMA integrity_check;")
	if err != nil {
		return fmt.Errorf("failed to prepare integrity_check statement: %w", err)
	}
	defer func() {
		finalizeErr := stmt.Finalize()
		err = errors.Join(err, finalizeErr)
	}()

	// integrity_check returns a single "ok" row when the database is
	// healthy, or one row per problem otherwise — the first row decides
	// pass/fail, so the result set need not be exhausted.
	row, err := stmt.Step()
	if err != nil {
		return fmt.Errorf("failed to execute integrity_check: %w", err)
	}
	if !row {
		return fmt.Errorf("integrity_check returned no rows")
	}

	result := stmt.ColumnText(0)
	if result != "ok" {
		return fmt.Errorf("integrity_check failed, result was: %s", result)
	}

	return nil
}
